spring.application.name=spring_boot_project_api

# database connection detail
spring.datasource.url=jdbc:postgresql://postgres:5432/tourism_db
spring.datasource.username=postgres
spring.datasource.password=tourism

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# redis detail
spring.data.redis.host=redis
spring.data.redis.port=6379

# Custom path for Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Custom path for raw OpenAPI JSON documentation
springdoc.api-docs.path=/api-docs

# Sort endpoints alphabetically
springdoc.swagger-ui.operationsSorter=alpha

# port for spring boot
server.port=8080